var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0012376b._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_de6a6ace._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_esm_build_templates_app-page_7bba165f.js")
R.c("server/chunks/ssr/[root-of-the-server]__04c73837._.js")
R.c("server/chunks/ssr/[root-of-the-server]__cc42ebc9._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_cbd4b7cd._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_app_a463d94a._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_app_layout_tsx_e44571ca._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_df5c1df3._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_builtin_forbidden_4d02233b.js")
R.c("server/chunks/ssr/ghana-trotro-admin__next-internal_server_app__not-found_page_actions_89b2b938.js")
R.m(73364)
module.exports=R.m(73364).exports
