var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/users/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__052fdcfd._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_de6a6ace._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_0bf76802._.js")
R.c("server/chunks/ssr/[root-of-the-server]__089cf6ac._.js")
R.c("server/chunks/ssr/[root-of-the-server]__cc42ebc9._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_cbd4b7cd._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_app_a463d94a._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_builtin_global-error_b844eacc.js")
R.c("server/chunks/ssr/ghana-trotro-admin_app_layout_tsx_e44571ca._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_df5c1df3._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_builtin_forbidden_4d02233b.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_builtin_unauthorized_6042660a.js")
R.c("server/chunks/ssr/13d57__next-internal_server_app_dashboard_users_page_actions_22aed0ee.js")
R.m(92358)
module.exports=R.m(92358).exports
