var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/notifications/create/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__7b54bb30._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_de6a6ace._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_ecfd0a03._.js")
R.c("server/chunks/ssr/[root-of-the-server]__089cf6ac._.js")
R.c("server/chunks/ssr/[root-of-the-server]__cc42ebc9._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_cbd4b7cd._.js")
R.c("server/chunks/ssr/ghana-trotro-admin_app_a463d94a._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_builtin_global-error_b844eacc.js")
R.c("server/chunks/ssr/ghana-trotro-admin_app_layout_tsx_e44571ca._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_df5c1df3._.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_builtin_forbidden_4d02233b.js")
R.c("server/chunks/ssr/8e6f2_next_dist_client_components_builtin_unauthorized_6042660a.js")
R.c("server/chunks/ssr/13d57__next-internal_server_app_dashboard_notifications_create_page_actions_082b43a5.js")
R.m(35168)
module.exports=R.m(35168).exports
